import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";
import { GeistSans, TitanOne } from "./fonts";

export const metadata: Metadata = {
  title: "TRAC Madison",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${TitanOne.variable} antialiased flex flex-col h-screen justify-between`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
